#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""RETIRED 2026-09-19. This is a tombstone. It builds nothing.

WHAT IT USED TO DO, AND WHY THAT WAS DANGEROUS
----------------------------------------------
It applied authored operations to a base spec and emitted an IFC. On 2026-09-18
both review engines found it still live, and the reproduction was exact:

    $ .venv-ifc314/Scripts/python.exe tools/layout/build_variant.py \\
          data/variants/v1-homestyler.json --no-render
      walls: 39   doors: 0   windows: 0   status: "reference_only"   EXIT=0

It built the permanently `reference_only` Homestyler SKETCH, at exit 0, from
`current_apartment_shell.json` - schema 0.1.0, **15 walls**, against a compiler
that resolves **25**. Its only guard refused a base whose status *starts with*
`RETIRED`; v1's base reads `from_developer_layout_via_cad_not_field_verified`,
so it sailed through. `check_variant_basis.py` refuses v1 correctly and with 23
seeds - and this path never asked it. **A gate only guards the door it is nailed
to.**

⚠️⚠️ WHY IT IS NOT MERELY SCHEMA-GUARDED
A schema guard that "accepts v2" would claim support that does not exist. This
implementation's operations, and `tools/ifc/model_from_spec.py` beneath them,
assume RECTANGULAR geometry - `x_m`, `y_m`, `length`, `horizontal`. Schema v2
carries REAL POLYGONS, including the mitred quadrilaterals `M2` and `M6b` that a
rectangle cannot express and would silently square off. Accepting v2 here would
produce confident, wrong geometry: worse than refusing.

⚠️ THIS IS NOT TO BE REPAIRED. The implementation is preserved in git history
(before 2026-09-19) if it is ever useful to read. The replacement is a NEW
compiler, built around:

    ResolvedGeometry
      + authored variant relations/operations
      -> resolved variant geometry
      -> IFC and views

⚠️ `v1-homestyler` IS `reference_only` AND IS NEVER BUILDABLE. It is a freehand
Homestyler sketch drawn over the same constructor raster v0 came from, before any
model existed. Owner, 2026-09-17: *"Homestyler is just for reference... I didn't
have any model, now I have a model. No direct, no exact dimensions, just general
ideas."* Its ideas survive - which room takes which role, that a laundry is
wanted, that a storage block should face two rooms. **Its coordinates are never
evidence, and no quantity, delta, wall position or area may come from it.**

REFUSAL CONTRACT
----------------
Every invocation exits non-zero, including `--all`. The refusal happens BEFORE
any base is read, any operation applied, any directory created and any output
written - so a refused run leaves every existing artefact byte-identical and
mtime-unchanged. `scripts/build_variant_retired_selftest.py` asserts exactly
that.
"""

import sys

EXIT_RETIRED = 2

MESSAGE = """\
REFUSED: tools/layout/build_variant.py is RETIRED as of 2026-09-19 and builds nothing.

WHY
  It emitted geometry from a rectangular schema (x_m / y_m / length / horizontal)
  while the compiler resolves REAL POLYGONS, including the mitred walls M2 and
  M6b that a rectangle cannot express. On 2026-09-18 it built the permanently
  reference_only v1-homestyler sketch at exit 0 - 39 walls, 0 doors, 0 windows -
  from a 15-wall schema-0.1.0 shell, because its only guard matched the literal
  string "RETIRED" on the base status.

  It is NOT schema-guarded to accept v2, because accepting v2 would claim support
  that does not exist: model_from_spec.py underneath it still assumes rectangles.

v1-homestyler
  reference_only, permanently, and NEVER buildable. A freehand sketch over the
  same raster v0 came from. Its ideas are useful; its coordinates are not
  evidence. check_variant_basis.py refuses it by design and that refusal is the
  correct permanent state, not a blocker to clear.

WHAT TO USE INSTEAD
  Nothing yet - the replacement is unbuilt, and that is deliberate. It must be a
  NEW compiler, not a repair of this one:

      ResolvedGeometry
        + authored variant relations/operations
        -> resolved variant geometry
        -> IFC and views

  The existing state is generated by tools/ifc/model_from_dxf.py from the gated
  DXF, and tools/layout/build_variant_spec.py compiles v0-existing/spec.json from
  ResolvedGeometry. Differencing two variants is tools/layout/check_variant_basis.py.

  The previous implementation is in git history before 2026-09-19. Read it if
  useful; do not restore it.

Nothing was read, created or written by this invocation.
"""


def main():
    # ⚠ THE REFUSAL IS THE FIRST THING THAT HAPPENS. No argument parsing that
    # could touch the filesystem, no base resolution, no mkdir, no write. A
    # retired builder that still creates an output directory is still a builder.
    sys.stderr.write(MESSAGE)
    return EXIT_RETIRED


if __name__ == "__main__":
    sys.exit(main())
